<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>cn.structured</groupId>
        <artifactId>structure-security-dependencies</artifactId>
        <version>1.1.0-SNAPSHOT</version>
        <relativePath>../structure-security-dependencies/pom.xml</relativePath>
    </parent>

    <groupId>cn.structured</groupId>
    <artifactId>structure-jwt-security-example</artifactId>
    <version>1.1.0-SNAPSHOT</version>

    <properties>
        <structure.version>1.3.5</structure.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-common</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.structured</groupId>
            <artifactId>structure-jwt-security-starter</artifactId>
            <version>1.1.0-SNAPSHOT</version>
        </dependency>
    </dependencies>


    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>


</project>
