<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>cn.structured</groupId>
        <artifactId>structure-dependencies</artifactId>
        <version>1.4.4</version>
    </parent>

    <name>structure-security-dependencies</name>
    <description>structure-security-dependencies</description>
    <artifactId>structure-security-dependencies</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <url>https://projects.structured.cn/structure-boot</url>
    <inceptionYear>2021</inceptionYear>
    <organization>
        <name>structure</name>
    </organization>
    <licenses>
        <license>
            <name>The Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>
    <developers>
        <developer>
            <id>chuckLcq</id>
            <name>chuck</name>
            <email>15524415221@163.com</email>
        </developer>
        <developer>
            <id>lchqJava</id>
            <name>Chuanqiang Liu</name>
            <email>361648887@qq.com</email>
        </developer>
    </developers>

    <issueManagement>
        <system>Github</system>
        <url>https://github.com/structure-projects/structure-security/issues</url>
    </issueManagement>

    <scm>
        <url>https://github.com/structure-projects/structure-security</url>
        <connection>scm:git:git://github.com/structure-projects/structure-security.git</connection>
        <developerConnection>scm:git:ssh://git@github.com:structure-projects/structure-security.git</developerConnection>
    </scm>


    <properties>
        <revision>1.1.5-SNAPSHOT</revision>
        <structure.version>1.4.2</structure.version>
        <spring-boot.version>4.0.6</spring-boot.version>
        <jjwt.version>0.12.7</jjwt.version>
        <jakarta.servlet.version>6.0.0</jakarta.servlet.version>
        <jakarta.annotation.version>2.1.1</jakarta.annotation.version>
        <lombok.version>1.18.30</lombok.version>
        <!-- jdk -->
        <charset>UTF-8</charset>
        <encoding>UTF-8</encoding>
        <java.version>17</java.version>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>${charset}</project.build.sourceEncoding>

        <!--maven-->
        <maven-plugin.version>3.8.1</maven-plugin.version>

        <maven-project-info-reports-plugin.version>3.0.0</maven-project-info-reports-plugin.version>
        <maven-site-plugin.version>3.7.1</maven-site-plugin.version>
        <maven-compiler-plugin.version>3.8.1</maven-compiler-plugin.version>
        <maven-source-plugin.version>2.2.1</maven-source-plugin.version>
        <maven-javadoc-plugin.version>3.6.3</maven-javadoc-plugin.version>
        <maven-gpg-plugin.version>1.5</maven-gpg-plugin.version>
        <cobertura-maven-plugin.version>2.7</cobertura-maven-plugin.version>
        <maven-flatten-maven-plugin.version>1.2.7</maven-flatten-maven-plugin.version>
        <central-publishing-maven-plugin.version>0.9.0</central-publishing-maven-plugin.version>
        <springdoc-openapi-starter-webmvc-api.version>2.3.0</springdoc-openapi-starter-webmvc-api.version>
    </properties>

    <modules>
        <module>../structure-security-core</module>
        <module>../structure-security-permission-starter</module>
        <module>../structure-security-jwt-starter</module>
        <module>../structure-security-basicauth-starter</module>
        <module>../structure-security-common</module>
        <module>../structure-security-oauth-sdk</module>
        <module>../structure-security-oauth-common</module>
        <module>../structure-security-oauth-resource-starter</module>
        <module>../structure-security-context-starter</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>cn.structured</groupId>
                <artifactId>structure-common</artifactId>
                <version>${structure.version}</version>
            </dependency>
            <dependency>
                <groupId>cn.structured</groupId>
                <artifactId>structure-security-common</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>cn.structured</groupId>
                <artifactId>structure-security-core</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>cn.structured</groupId>
                <artifactId>structure-security-permission-starter</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>cn.structured</groupId>
                <artifactId>structure-security-jwt-starter</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>cn.structured</groupId>
                <artifactId>structure-security-basicauth-client</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>cn.structured</groupId>
                <artifactId>structure-security-basicauth-sterter</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
            <dependency>
                <groupId>jakarta.servlet</groupId>
                <artifactId>jakarta.servlet-api</artifactId>
                <version>${jakarta.servlet.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>jakarta.annotation</groupId>
                <artifactId>jakarta.annotation-api</artifactId>
                <version>${jakarta.annotation.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-api</artifactId>
                <version>${springdoc-openapi-starter-webmvc-api.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>

