<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>


    <groupId>cn.structured</groupId>
    <name>structure-security-dependencies</name>
    <description>structure-security-dependencies</description>
    <artifactId>structure-security-dependencies</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <url>https://projects.structured.cn/structure-boot</url>
    <inceptionYear>2021</inceptionYear>
    <organization>
        <name>structure</name>
    </organization>
    <licenses>
        <license>
            <name>The Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>
    <developers>
        <developer>
            <id>chuckLcq</id>
            <name>chuck</name>
            <email>15524415221@163.com</email>
        </developer>
        <developer>
            <id>lchqJava</id>
            <name>Chuanqiang Liu</name>
            <email>361648887@qq.com</email>
        </developer>
    </developers>

    <issueManagement>
        <system>Github</system>
        <url>https://github.com/structure-projects/structure-security/issues</url>
    </issueManagement>

    <scm>
        <url>https://github.com/structure-projects/structure-security</url>
        <connection>scm:git:git://github.com/structure-projects/structure-security.git</connection>
        <developerConnection>scm:git:ssh://git@github.com:structure-projects/structure-security.git</developerConnection>
    </scm>


    <properties>
        <revision>1.1.0-SNAPSHOT</revision>
        <structure.version>1.3.6-SNAPSHOT</structure.version>
        <spring-boot.version>4.0.6</spring-boot.version>
        <spring-security.version>6.2.3</spring-security.version>
        <jjwt.version>0.12.7</jjwt.version>
        <jakarta.servlet.version>6.0.0</jakarta.servlet.version>
        <jakarta.annotation.version>2.1.1</jakarta.annotation.version>
        <lombok.version>1.18.30</lombok.version>
        <!-- jdk -->
        <charset>UTF-8</charset>
        <encoding>UTF-8</encoding>
        <java.version>17</java.version>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>${charset}</project.build.sourceEncoding>

        <!--maven-->
        <maven-plugin.version>3.8.1</maven-plugin.version>

        <maven-project-info-reports-plugin.version>3.0.0</maven-project-info-reports-plugin.version>
        <maven-site-plugin.version>3.7.1</maven-site-plugin.version>
        <maven-compiler-plugin.version>3.8.1</maven-compiler-plugin.version>
        <maven-source-plugin.version>2.2.1</maven-source-plugin.version>
        <maven-javadoc-plugin.version>3.6.3</maven-javadoc-plugin.version>
        <maven-gpg-plugin.version>1.5</maven-gpg-plugin.version>
        <cobertura-maven-plugin.version>2.7</cobertura-maven-plugin.version>
        <maven-flatten-maven-plugin.version>1.2.7</maven-flatten-maven-plugin.version>
        <central-publishing-maven-plugin.version>0.9.0</central-publishing-maven-plugin.version>
    </properties>

    <modules>
        <module>../structure-security-core</module>
        <module>../structure-jwt-security-starter</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>cn.structured</groupId>
                <artifactId>structure-common</artifactId>
                <version>${structure.version}</version>
            </dependency>
            <dependency>
                <groupId>cn.structured</groupId>
                <artifactId>structure-security-core</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>cn.structured</groupId>
                <artifactId>structure-jwt-security-starter</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
            <dependency>
                <groupId>jakarta.servlet</groupId>
                <artifactId>jakarta.servlet-api</artifactId>
                <version>${jakarta.servlet.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>jakarta.annotation</groupId>
                <artifactId>jakarta.annotation-api</artifactId>
                <version>${jakarta.annotation.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.security</groupId>
                <artifactId>spring-security-bom</artifactId>
                <version>${spring-security.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-plugin-plugin</artifactId>
                    <version>${maven-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-site-plugin</artifactId>
                    <version>${maven-site-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-project-info-reports-plugin</artifactId>
                    <version>${maven-project-info-reports-plugin.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>${maven-flatten-maven-plugin.version}</version>
                <configuration>
                    <flattenedPomFilename>pom-xml-flattened</flattenedPomFilename>
                    <updatePomFile>true</updatePomFile>
                    <!-- 使用 oss 模式适合发布到 Maven 中央仓库的 jar 包 -->
                    <flattenMode>oss</flattenMode>
                </configuration>
                <executions>
                    <execution>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>flatten-clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <release>${java.version}</release>
                </configuration>
            </plugin>
            <!-- Javadoc -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>${maven-javadoc-plugin.version}</version>
                <configuration>
                    <source>${java.version}</source>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <charset>${charset}</charset>
                    <docencoding>${charset}</docencoding>
                    <show>private</show>
                    <nohelp>true</nohelp>
                    <links>
                        <link>https://docs.oracle.com/en/java/javase/${java.version}/docs/api/</link>
                    </links>
                    <additionalOptions>
                        <additionalOption>-Xdoclint:none</additionalOption>
                    </additionalOptions>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <!-- Source -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>${maven-source-plugin.version}</version>
                <executions>
                    <execution>
                        <id>oss</id>
                        <phase>package</phase>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>cobertura-maven-plugin</artifactId>
                <version>${cobertura-maven-plugin.version}</version>
                <configuration>
                    <formats>
                        <format>html</format>
                        <format>xml</format>
                    </formats>
                    <check/>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>release</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.sonatype.central</groupId>
                        <artifactId>central-publishing-maven-plugin</artifactId>
                        <version>${central-publishing-maven-plugin.version}</version>
                        <extensions>true</extensions>
                        <configuration>
                            <publishingServerId>oss</publishingServerId>
                            <autoPublish>true</autoPublish>
                            <waitUntil>validated</waitUntil> <!-- 不阻塞构建进程 -->
                            <!--  <waitUntil>published</waitUntil>-->
                            <waitMaxTime>3600</waitMaxTime>
                            <waitPollingInterval>10</waitPollingInterval>
                        </configuration>
                    </plugin>

                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-source-plugin</artifactId>
                        <version>${maven-source-plugin.version}</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>jar-no-fork</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                        <version>${maven-javadoc-plugin.version}</version>
                        <configuration>
                            <source>${java.version}</source>
                            <encoding>${project.build.sourceEncoding}</encoding>
                            <charset>${charset}</charset>
                            <docencoding>${charset}</docencoding>
                            <show>private</show>
                            <nohelp>true</nohelp>
                            <links>
                                <link>https://docs.oracle.com/en/java/javase/${java.version}/docs/api/</link>
                            </links>
                            <additionalOptions>
                                <additionalOption>-Xdoclint:none</additionalOption>
                            </additionalOptions>
                        </configuration>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <version>${maven-gpg-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <gpgArguments>
                                <arg>--pinentry-mode</arg>
                                <arg>loopback</arg>
                            </gpgArguments>
                            <passphrase>${GPG_PASSPHRASE}</passphrase>  <!-- 直接使用环境变量 -->
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
    <!-- 2. 配置仓库分发地址 -->
    <distributionManagement>
        <snapshotRepository>
            <id>oss</id>
            <url>https://central.sonatype.com/repository/maven-snapshots/</url>
        </snapshotRepository>
        <!-- 注意：快照部署不需要配置<repository>（那是给正式版用的） -->
    </distributionManagement>

    <repositories>
        <repository>
            <id>ossrh-snapshots</id>
            <url>https://central.sonatype.com/repository/maven-snapshots/</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
</project>

