<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>cn.structured</groupId>
        <artifactId>structure-security-dependencies</artifactId>
        <version>${revision}</version>
        <relativePath>../structure-security-dependencies/pom.xml</relativePath>
    </parent>

    <artifactId>structure-security-samples</artifactId>
    <packaging>pom</packaging>
    <name>structure-security-samples</name>
    <description>Structure Security Examples and Samples</description>

    <!-- 禁止发布示例工程到 Maven 中央仓库 -->
    <properties>
        <maven.deploy.skip>true</maven.deploy.skip>
    </properties>

    <modules>
        <module>./structure-security-jwt-example</module>
        <module>./structure-security-permission-sample</module>
        <module>./structure-security-oauth-resource-example</module>
        <module>./structure-security-basicauth-server-sample</module>
        <module>./structure-security-context-sample</module>
        <module>./structure-security-core-sample</module>
    </modules>

    <!-- 示例工程额外依赖管理（父 POM 未覆盖的） -->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>cn.structured</groupId>
                <artifactId>structure-restful-web-starter</artifactId>
                <version>${structure.version}</version>
            </dependency>
            <dependency>
                <groupId>cn.structured</groupId>
                <artifactId>structure-redis-starter</artifactId>
                <version>${structure.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <parameters>true</parameters>
                </configuration>
            </plugin>
        </plugins>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <executions>
                        <execution>
                            <goals>
                                <goal>repackage</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

</project>
